services:
    # Emojihub service
    emojihub:
        build:
            context: ./emojihub
            dockerfile: Dockerfile
        expose:
            - 4000
        networks:
            private_network:
                ipv4_address: 172.28.0.5

    # Redis-cache service
    redis-cache:
        image: "redis:latest"
        restart: always
        expose:
            - 6379
        networks:
            private_network:
                ipv4_address: 172.28.0.4
        volumes:
            - cache:/data

    # Myapp service
    myapp:
        build:
            context: ./myapp
            dockerfile: Dockerfile
        networks:
            private_network:
                ipv4_address: 172.28.0.3
        depends_on:
            - emojihub
            - redis-cache
        expose:
            - 3000
        environment:
            - OPENAI_API_KEY=<ENTER_KEY_HERE>
            - EMOJIHUB_HOST=http://emojihub
            - EMOJIHUB_PORT=4000
            - REDIS_HOST=redis-cache
            - REDIS_PORT=6379
            - REDIS_CONNECTION_TIMEOUT=5000

    # Emoji-story service
    emoji-story:
        build:
            context: ./emoji-story
            dockerfile: Dockerfile
        ports:
            - "3001:80"
        networks:
            private_network:
                ipv4_address: 172.28.0.2
        depends_on:
            - myapp
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - REACT_APP_API_ENDPOINT=172.28.0.3:3000

# Custom Docker network with subnet decleration
networks:
    private_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.1

# Docker volume for cache
volumes:
    cache:
        driver: local
